import os
from dotenv import load_dotenv
load_dotenv()
from typing import List
from pydantic import BaseModel, Field

from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from tavily import TavilyClient
from langchain_nvidia_ai_endpoints import ChatNVIDIA
from openai import OpenAI
from langchain_tavily import TavilySearch

NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")
if not NVIDIA_API_KEY:
    raise RuntimeError("NVIDIA_API_KEY is missing from .env or environment")

# ... then pass it to clients
client = OpenAI(
    base_url="https://integrate.api.nvidia.com/v1",
    api_key=NVIDIA_API_KEY)

class Source(BaseModel):
    """Schema for a source used by the agent."""
    url:str = Field(description="The URL of the source")

class AgentResponse(BaseModel):
    """Schema for the agent's response."""
    answer: str = Field(description="The answer generated by the agent")
    sources: List[Source] = Field(default_factory=list,description="List of sources used to generate the answer")


# llm = ChatOpenAI(model="gpt-3.5-turbo")
llm = ChatNVIDIA(model="meta/llama-3.3-70b-instruct",api_key=NVIDIA_API_KEY)
tools = [TavilySearch()]
agent = create_agent(tools=tools, model=llm,response_format=AgentResponse)

def main():
    print("Hello from langchain-course!")
    result = agent.invoke({"messages": HumanMessage(content="Search for 3 AI developers job in london area in linkedin with details")})
    print(result)


if __name__ == "__main__":
    main()
